---
- name: "Common - Systemd-resolved - Backup resolv.conf"
  archive:
    path: "resolv.conf"
    dest: "resolv.conf.{{ ansible_date_time.iso8601_basic_short }}.org.gz"
    format: gz
  when: ansible_dns.nameservers[0] is defined and ansible_dns.nameservers[0] != "127.0.0.53"
  tags: [ common, resolved ]

- name: "Common - Systemd-resolved - Backup {{ resolvedconffile }}"
  archive:
    path: "{{ resolvedconffile }}"
    dest: "{{ resolvedconffile }}.{{ ansible_date_time.iso8601_basic_short }}.org.gz"
    format: gz
  when: ansible_dns.nameservers[0] is defined and ansible_dns.nameservers[0] != "127.0.0.53"
  tags: [ common, resolved ]

- name: "Common - Systemd-resolved - Upload Resolved Config"
  template:
    src: "{{ ansible_distribution }}_resolved.conf.j2"
    dest: "{{ resolvedconffile }}"
  when: ansible_dns.nameservers[0] is defined and ansible_dns.nameservers[0] != "127.0.0.53"
  tags: [ common, resolved ]

- name: "Common - Systemd-resolved - Delete file /etc/resolv.conf"
  file:
    path: /etc/resolv.conf
    state: absent
  when: ansible_dns.nameservers[0] is defined and ansible_dns.nameservers[0] != "127.0.0.53"
  tags: [ common, resolved ]

- name: "Common - Systemd-resolved - Service enabled and reloaded"
  systemd:
    name: "systemd-resolved"
    enabled: yes
    masked: no
    state: started
    daemon_reload: yes
  when: ansible_dns.nameservers[0] is defined and ansible_dns.nameservers[0] != "127.0.0.53"
  tags: [ common, resolved ]

- name: "Common - Systemd-resolved - Create resolv.conf symbolic link"
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
  when: ansible_dns.nameservers[0] is defined and ansible_dns.nameservers[0] != "127.0.0.53"
  tags: [ common, resolved ]
  notify:
  - restart resolved
