---
all:
  children:
    mygroup:
      hosts:
        SRD1POD1:
          ansible_host: 10.0.0.1
        SRD2POD2:
          ansible_host: 10.0.0.2
      vars:
          gather_facts: false
    sbx:
      hosts:
        sbxnxos:
          ansible_host: sbx-nxos-mgmt.cisco.com
#          ansible_connection: httpapi
          ansible_connection: network_cli
          ansible_httpapi_remote_user: admin
          ansible_httpapi_password: 'Admin_1234!'
          ansible_httpapi_port: 443
          ansible_httpapi_use_ssl: yes
          ansible_httpapi_validate_certs: no
          ansible_network_os: nxos
#          ansible_network_os: nxos
#          ansible_network_os: cisco.nxos.nxos
#          ansible_connection: httpapi
#          ansible_connection: ansible.netcommon.network_cli
#          ansible_user: admin
