ansible_user: root

prometheus_link: https://github.com/prometheus/prometheus/releases/download/v2.21.0/prometheus-2.21.0.linux-amd64.tar.gz
alertmanager_link: https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
nodeexporter_link: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
snmpexporter_link: https://github.com/prometheus/snmp_exporter/releases/download/v0.19.0/snmp_exporter-0.19.0.linux-amd64.tar.gz
prometheus_dir: /opt/prometheus
alertmanager_dir: /opt/alertmanager
nodeexporter_dir: /opt/nodeexporter
snmpexporter_dir: /opt/snmpexporter
systemd_dir: /usr/lib/systemd/system

alertmanager_address: localhost

scrape: 5s
evaluation: 5s

smtp_server: smtp.gmail.com
smtp_port: 587
from_address: user01@gmail.com
smtp_username: user01@gmail.com
smtp_pass: CHANGEME
#smtp_pass: !vault |
#          $ANSIBLE_VAULT;1.1;AES256

send_to:
  - user01@gmail.com

prometheus_hosts:
  - 192.168.0.100
  - 192.168.0.101
