- name: "{{ ansible_network_os }} - {{ inventory_hostname }} configuration backup"
  cisco.ios.ios_config:
    backup: yes
    backup_options:
      filename: "{{ inventory_hostname }}-{{ lookup('pipe','date +%Y%m%d%H%M%S') }}-backup.cfg"
      dir_path: "{{ resultdir }}"
  tags: [ cisco, ios ]
#  when: ansible_network_os == "ios"
  vars:
    - gather_facts: no

- name: "{{ ansible_network_os }} - Dump Inventory vars to File"
  copy: content="{{ hostvars[inventory_hostname] }}" dest="{{ resultdir }}/{{ inventory_hostname }}-{{ lookup('pipe','date +%Y%m%d%H%M%S') }}-inventoryvars.cfg"
  tags: [ cisco, ios ]

- name: "{{ ansible_network_os }} - Get Facts - all"
  ios_facts:
    gather_subset: all
#    gather_subset: "!config"
  tags: [ cisco, ios ]
  register: "iosfacts"
- name: "{{ ansible_network_os }} - Dump Facts to File - all"
  copy: content="{{ iosfacts }}" dest="{{ resultdir }}/{{ inventory_hostname }}-{{ lookup('pipe','date +%Y%m%d%H%M%S') }}-facts.cfg"
  tags: [ cisco, ios ]

- name: "{{ ansible_network_os }} - Get Facts - config"
  ios_facts:
    gather_subset: "config"
  tags: [ cisco, ios ]
  register: "iosfactsconfig"
- name: "{{ ansible_network_os }} - Dump Facts to File - config"
  copy: content="{{ iosfactsconfig }}" dest="{{ resultdir }}/{{ inventory_hostname }}-{{ lookup('pipe','date +%Y%m%d%H%M%S') }}-facts-config.cfg"
  tags: [ cisco, ios ]

- name: "{{ ansible_network_os }} - Get Facts - default"
  ios_facts:
    gather_subset: "default"
  tags: [ cisco, ios ]
  register: "iosfactsdefault"
- name: "{{ ansible_network_os }} - Dump Facts to File - default"
  copy: content="{{ iosfactsdefault }}" dest="{{ resultdir }}/{{ inventory_hostname }}-{{ lookup('pipe','date +%Y%m%d%H%M%S') }}-facts-default.cfg"
  tags: [ cisco, ios ]

- name: "{{ ansible_network_os }} - Get Facts - hardware"
  ios_facts:
    gather_subset: "hardware"
  tags: [ cisco, ios ]
  register: "iosfactshardware"
- name: "{{ ansible_network_os }} - Dump Facts to File - hardware"
  copy: content="{{ iosfactshardware }}" dest="{{ resultdir }}/{{ inventory_hostname }}-{{ lookup('pipe','date +%Y%m%d%H%M%S') }}-facts-hardware.cfg"
  tags: [ cisco, ios ]

- name: "{{ ansible_network_os }} - Get Facts - interfaces"
  ios_facts:
    gather_subset: "interfaces"
  tags: [ cisco, ios ]
  register: "iosfactsinterfaces"
- name: "{{ ansible_network_os }} - Dump Facts to File - interfaces"
  copy: content="{{ iosfactsinterfaces }}" dest="{{ resultdir }}/{{ inventory_hostname }}-{{ lookup('pipe','date +%Y%m%d%H%M%S') }}-facts-interfaces.cfg"
  tags: [ cisco, ios ]
