---
- name: "PHP - {{ ansible_distribution }} - Packages install"
  package:
    name:
      - php-fpm
      - php-pgsql
    state: present
  tags: [ php, packages ]

- name: "PHP - {{ ansible_distribution }} - Upload index.php"
  template:
    src: "{{ ansible_distribution }}_nginx_index.php.j2"
    dest: "{{ nginxwebroot }}/index.php"
  tags: [ php, nginx, debian, config ]

- name: "PHP - {{ ansible_distribution }} - Upload style.css"
  template:
    src: "{{ ansible_distribution }}_nginx_style.css.j2"
    dest: "{{ nginxwebroot }}/style.css"
  tags: [ php, nginx, debian, config ]

- name: "PHP - {{ ansible_distribution }} - NGINX Config import"
  template:
    src: "{{ ansible_distribution }}_nginx_php.conf.j2"
    dest: "/etc/nginx/sites-available/{{ nginxconffile }}"
  tags: [ php, nginx, debian, config ]
  notify:
  - restart nginx

