- name: "Configure ip helpers on multiple interfaces"
  ios_config:
    lines:
      - ip helper-address 10.0.0.254
      - ip helper-address 10.0.0.253
    parents: "{{ item }}"
  with_items:
    - interface Ethernet1
    - interface Ethernet2
    - interface GigabitEthernet1

