- name: "{{ ansible_distribution }} - Packages - Install apt-transport-https"
  apt:
    name: [ 'python3-apt', 'python-apt', 'apt-transport-https' ]
    update_cache: yes
  tags: [ debian, packages ]

# Add specified repository into sources list
- name: "{{ ansible_distribution }} - Packages - Add APT repository"
  apt_repository:
    repo: '{{ item }}'
    state: present
  with_items:
    - '{{ aptsourcesadd }}'
  tags: [ debian, packages ]

# Remove specified repository from sources list
- name: "{{ ansible_distribution }} - Packages - Remove APT repository"
  apt_repository:
    repo: '{{ item }}'
    state: absent
  with_items: 
    - "{{ aptsourcesdel }}"
  tags: [ debian, packages ]

