- name: "Common - Systemd-journald - Ensure persistent storage of log messages is enabled"
  file:
    path: "/var/log/journal"
    state: directory
    owner: root
    group: systemd-journal
    mode: 02755
  notify:
  - create tmpfiles journald
  - restart journald
  tags: [ common, journald, systemd ]

