- name: "{{ ansible_distribution }} - Network - Ensure localtime is CEST"
  file:
    src: "/usr/share/zoneinfo/{{ localtime }}"
    dest: "/etc/localtime"
    owner: root
    group: root
    state: link
  tags: [ common, timezone ]

