---
- name: "{{ ansible_distribution }} - Packages - Install extra epel packages"
  shell: |
    EPEL_SCREEN_DIR="{{ linuxmirror }}/fedora/epel/8/Everything/x86_64/Packages/s/"
    EPEL_SCREEN_PACKAGE=$(curl -s ${EPEL_SCREEN_DIR} | grep screen-[0-9] | sed "s/.*\(\"screen.*rpm\"\).*/\1/" | sed "s/\"//g")
    EPEL_SCREEN_URL="${EPEL_SCREEN_DIR}${EPEL_SCREEN_PACKAGE}"
    #
    EPEL_HAVEGED_DIR="{{ linuxmirror }}/fedora/epel/8/Everything/x86_64/Packages/h/"
    EPEL_HAVEGED_PACKAGE=$(curl -s ${EPEL_HAVEGED_DIR} | grep haveged-[0-9] | sed 's/.*\(\"haveged.*rpm\"\).*/\1/' | sed 's/\"//g')
    EPEL_HAVEGED_URL="${EPEL_HAVEGED_DIR}${EPEL_HAVEGED_PACKAGE}"
    #
    EPEL_HTOP_DIR="{{ linuxmirror }}/fedora/epel/8/Everything/x86_64/Packages/h/"
    EPEL_HTOP_PACKAGE=$(curl -s ${EPEL_HTOP_DIR} | grep htop-[0-9] | sed "s/.*\(\"htop.*rpm\"\).*/\1/" | sed "s/\"//g")
    EPEL_HTOP_URL="${EPEL_HTOP_DIR}${EPEL_HTOP_PACKAGE}"
    #
    EPEL_IFTOP_DIR="{{ linuxmirror }}/fedora/epel/8/Everything/x86_64/Packages/i/"
    EPEL_IFTOP_PACKAGE=$(curl -s ${EPEL_IFTOP_DIR} | grep iftop-[0-9] | sed "s/.*\(\"iftop.*rpm\"\).*/\1/" | sed "s/\"//g")
    EPEL_IFTOP_URL="${EPEL_IFTOP_DIR}${EPEL_IFTOP_PACKAGE}"
    #
    yum install -y ${EPEL_SCREEN_URL} ${EPEL_HAVEGED_URL} ${EPEL_HTOP_URL} ${EPEL_IFTOP_URL}
  args:
    executable: /bin/bash
  tags: [ centos, packages ]

