- name: "NGINX - {{ ansible_distribution }} - Backup /etc/nginx/nginx.conf"
  archive:
    path: /etc/nginx/nginx.conf
    dest: nginx.conf.{{ ansible_date_time.iso8601_basic_short }}.org.gz
    format: gz
  tags: [ common, centos, archive ]

- name: "NGINX - {{ ansible_distribution }} - Create SSL directory"
  file:
    path: "/etc/pki/nginx/private"
    state: directory
    mode: 02755
  tags: [ nginx, centos, ssl ]

- name: "NGINX - {{ ansible_distribution }} - Generate Certificate"
  command : openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/pki/nginx/private/server.key -out /etc/pki/nginx/server.crt -subj "/C=FR/ST=OCCITANIE/L=TOULOUSE/CN={{ hostname.short }}.{{ hostname.domain }}"
  tags: [ nginx, centos, ssl ]

- name: "NGINX - {{ ansible_distribution }} - Config import"
  template:
    src: "{{ ansible_distribution }}_nginx.conf"
    dest: /etc/nginx/nginx.conf
  tags: [ nginx, centos, config ]
  notify:
  - restart nginx

