- name: "NGINX - {{ ansible_distribution }} - Backup /etc/nginx/nginx.conf"
  archive:  
    path: "/etc/nginx/sites-available/{{ nginxconffile }}"
    dest: "{{ nginxconffile }}.{{ ansible_date_time.iso8601_basic_short }}.org.gz"
    format: gz
  tags: [ common, debian, archive ]

- name: "NGINX - {{ ansible_distribution }} - Config import"
  template:
    src: "{{ ansible_distribution }}_nginx.conf"
    dest: "/etc/nginx/sites-available/{{ nginxconffile }}"
  tags: [ nginx, debian, config ]

- name: "NGINX - {{ ansible_distribution }} - Delete default symlink"
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags: [ nginx, debian, config ]

- name: "NGINX - {{ ansible_distribution }} - create new config symlink"
  file:
    src: "/etc/nginx/sites-available/{{ nginxconffile }}"
    dest: "/etc/nginx/sites-enabled/{{ nginxconffile }}"
    state: link
  tags: [ nginx, debian, config ]
  notify:
  - restart nginx

