- name: "PHP - {{ ansible_distribution }} - Packages install"
  package:
    name:
      - php-fpm
      - php-pgsql
    state: present
  tags: [ php, packages ]

- name: "PHP - {{ ansible_distribution }} - NGINX Config import"
  template:
    src: "{{ ansible_distribution }}_nginx_php.conf"
    dest: "/etc/nginx/sites-available/{{ nginxconffile }}"
  tags: [ nginx, debian, config ]
  notify:
  - restart nginx

