---
- name: "Common - Network - CIDR conversion"
  set_fact:
    mask_cidr: "{{ ip | ipaddr('prefix') }}"
  vars:
    ip: "{{ ansible_default_ipv4.address }}/{{ansible_default_ipv4.netmask }}"
  tags: [ common, never, nftables ]

- name: "Common - Network - Ensure nftables is installed"
  package:
    name: "nftables"
    state: present
  tags: [ common, never, nftables ]

- name: "Common - Backup - {{ nftablesconffile }}"
  archive:
    path: "{{ nftablesconffile }}"
    dest: "{{ nftablesconffile }}.{{ ansible_date_time.iso8601_basic_short }}.org.gz"
    format: gz
  tags: [ common, never, nftables ]

- name: "Common - Network - NFtables firewall"
  template:
    src: "{{ ansible_distribution }}_nftables.conf.j2"
    dest: "{{ nftablesconffile }}"
  tags: [ common, never, nftables ]

- name: "Common - Services - nftables enable and reload"
  systemd:
    name: "nftables"
    enabled: yes
    masked: no
    state: started
    daemon_reload: yes
  tags: [ common, never, nftables ]
