---
- name: "Common - Systemd-timesyncd - Check that the /etc/systemd/timesyncd.conf exists"
  stat:
    path: "{{ timesyncdconffile }}"
  register: tsyncdfile
  tags: [ common, timesyncd ]

- name: "Common - Systemd-timesyncd - Timesyncd conf file update"
  lineinfile:
    path: "{{ timesyncdconffile }}"
    regexp: "^#?NTP="
    line: "NTP={{ ntp_server }}"
  tags: [ common, timesyncd ]
  when: tsyncdfile.stat.exists
  notify:
  - restart timesyncd

