ansible_user: root

localtime: "Europe/Paris"

ntp_server: 195.83.132.135

newuser: admin

mtu: 1400

resolvedconffile: "/etc/systemd/resolved.conf"
timesyncdconffile: "/etc/systemd/timesyncd.conf"

commonpackages:
  - bash-completion
  - tmux
  - wget
  - rsyslog
  - postfix
  - sudo
  - qemu-guest-agent
  - tcpdump
  - psmisc
  - xauth
  - nftables

linuxmirror: "https://mirrors.ircam.fr/pub"

gitlaburl: "https://gitlab.com/nicolasi31/public/-/raw/master"

persoconffiles:
  - .tmux.conf
  - .screenrc
  - .vimrc

persoscripts:
  - perso-00-enabled.sh
  - perso-alias_and_variables.sh
  - perso-cat_functions.sh
  - perso-cisco.sh
  - perso-cloud-hypervisor.sh
  - perso-dash.sh
  - perso-distrib.sh
  - perso-download.sh
  - perso-firecracker.sh
  - perso-freebox.sh
  - perso-genfile.sh
  - perso-kvm.sh
  - perso-mail.sh
  - perso-miscfunctions.sh
  - perso-mm-ipradio.sh
  - perso-mm-iptv4sat.sh
  - perso-mm-iptv.sh
  - perso-network.sh
  - perso-nftables.sh
  - perso-per_arch.sh
  - perso-persoscripts.sh
  - perso-podcast.sh
  - perso-ps_and_ls_colors.sh
  - perso-pxe.sh
  - perso-sauvegarde.sh
  - perso-tipsdatabase.sh
  - perso-tipsgnome.sh
  - perso-tipskvm.sh
  - perso-tipsmultimedia.sh
  - perso-tipsnewinstall.sh
  - perso-tipswindows.sh
  - perso-usbkey.sh

