# /usr/bin/perl ~/.config/openbox/random-nasa-wallpaper.pl &
# killall conky urxvtd xscreensaver
# /usr/bin/conky -d
# /usr/bin/urxvtd -q -f
# /usr/bin/xscreensaver &

# /usr/bin/synclient VertEdgeScroll=1 TapButton1=1 TapButton2=2 TapButton3=3

# xrdb -merge ~/.Xresources
# xmodmap ~/.Xmodmap

# /usr/bin/xset s off
# /usr/bin/xset m 4/2 0
# /usr/bin/xhost +serveur
# /usr/bin/setxkbmap -option terminate:ctrl_alt_bksp

# pcmanfm --desktop &

# exec /usr/bin/fluxbox
# exec /usr/bin/twm
# exec /usr/local/bin/enlightenment_start
# exec /usr/bin/openbox-session
# exec /usr/bin/i3
# exec /usr/bin/sway

# pulseaudio -D
# exec /usr/bin/mate-session

# exec /usr/bin/startkde

exec /usr/bin/gnome-session
